# Euler Problem #44

#Pentagon numbers:
# P(n) = n*(3*n-1)/2 

# Pentagonal numbers are generated by the formula, 
# . The first ten pentagonal numbers are:

# It can be seen that P4 + P7 = 22+70=92=P8
# . However, their difference, 70-22=48 
# , is not pentagonal.

# TASK: 
# Find the pair of pentagonal numbers, P(j) and P(k), 
# for which their sum and difference are pentagonal and    D = | Pk - Pj |  is minimised; 
# what is the value of  D ?

def get_penta_num ( num ):
    # return the pentagonal number generated from the given parameter
    return num*( 3*num - 1) / 2

def is_penta_num ( num):
    # check that the given parameter is pentagonal
    # method: invert the pentagonal equation, and if an integer comes out, is True
    # else: return False

    # TODO: develop inverted formula
    return False
